version: 2.1
#orbs:
#  singularity: singularity/singularity@1.0.10

jobs:
  build:
        machine: true
        steps:
                - checkout
                - run: sudo apt-get install graphviz
                - run: cd ~ ; wget -qO- get.nextflow.io | bash ; chmod 755 nextflow ; sudo ln -s ~/nextflow /usr/local/bin/ 
                - run: echo " docker.runOptions = '-u $(id -u):$(id -g)' " > ~/.nextflow/config
                #; sudo apt-get install libarchive-dev
#                - run: sudo rm -rf /usr/local/go
#                - run: cd ~ ; export VERSION=1.13 OS=linux ARCH=amd64; wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz; sudo tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz ; rm go$VERSION.$OS-$ARCH.tar.gz; sudo ln -s /usr/local/go/bin/go /usr/local/bin/
#                - run: which go; go version; go env
#                - run: cd ~ ; VERSION=3.6.0; wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz; tar -xzf singularity-${VERSION}.tar.gz; cd singularity; ./mconfig; make -C builddir; sudo make -C builddir install                         
#                - run: cd ~ ; singularity pull quantiseq2.img shub://IARCbioinfo/quantiseq-nf:v1.1
                - run: cd ~ && git clone https://github.com/iarcbioinfo/data_test.git
                - run: cd ~ && git clone -b v2.3 https://github.com/iarcbioinfo/RNAseq-nf.git
                - run: cd ; nextflow run RNAseq-nf/ -profile docker --input_folder ~/data_test/FASTQ/ --output_folder BAM_realigned --ref_folder  ~/data_test/REF --gtf ~/data_test/REF/TP53_small.gtf --bed ~/data_test/BED/TP53_small.bed --cpu 2 --mem 4
                - run: cd ; nextflow run ~/project/ --help
                - run: cd ; docker pull trinityctat/starfusion:1.9.0
                - run: cd ; nextflow run ~/project/ -with-docker trinityctat/starfusion:1.9.0 --input_folder ~/data_test/FASTQ/ --output_folder RNAseq-fusion-out --CTAT_folder ~/data_test/REF/ctat_genome_lib_build_dir_TP53/ --fastq_ext fastq.gz --cpu 2 --mem 4 -with-dag dag.html
                - run: cd ; nextflow run ~/project/ -with-docker trinityctat/starfusion:1.9.0 --input_folder ~/data_test/FASTQ/ --output_folder RNAseq-fusion-out --CTAT_folder ~/data_test/REF/ctat_genome_lib_build_dir_TP53/ --fastq_ext fastq.gz --cpu 2 --mem 4 -resume -with-dag dag.png
                - run: cd ; echo -e 'SM\tpair1\tpair2\tjunction\nNA06984\tdata_test/FASTQ/NA06984_T_1.fastq.gz\tdata_test/FASTQ/NA06984_T_2.fastq.gz\tnone\nNA06984_2RG\tdata_test/FASTQ/NA06984_T_RG1_1.fastq.gz\tdata_test/FASTQ/NA06984_T_RG1_2.fastq.gz\tnone\nNA06984_2RG\tdata_test/FASTQ/NA06984_T_RG2_1.fastq.gz\tdata_test/FASTQ/NA06984_T_RG2_2.fastq.gz\tnone' > input.txt ; nextflow run ~/project/ -with-docker trinityctat/starfusion:1.9.0 --input_file input.txt --output_folder RNAseq-fusion-out --CTAT_folder ~/data_test/REF/ctat_genome_lib_build_dir_TP53/ --fastq_ext fastq.gz --cpu 2 --mem 4
                - run: cd ; cp ~/dag.* ~/project/.
                - add_ssh_keys:
                                fingerprints:
                                        - "2d:55:7c:ec:4c:fc:32:25:ff:20:cb:08:a8:ee:e4:bc"
                - deploy:
                        branch: [master, dev]
                        command: chmod +x deploy.sh && ./deploy.sh

workflows:
  install_s_build_and_test:
    jobs:
      - build